name: Dell Main Models
version: 0.0.1
schema: v1

models:
  # NPU models
  - name: NPU FIM Autocomplete
    provider: openai
    model: npu-fim-qwen25-coder-0p5b
    apiBase: http://localhost:4001/v1
    useLegacyCompletionsEndpoint: true
    roles:
      - autocomplete
    autocompleteOptions:
      debounceDelay: 200
      maxPromptTokens: 1024
      onlyMyCode: true

  - name: NPU Instruct
    provider: openai
    model: npu-chat-qwen25-coder-0p5b-instruct
    apiBase: http://aperture/v1
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      temperature: 0.2
      maxTokens: 2048

  # GB10 models
  - name: GB10 Coder
    provider: openai
    model: qwen3-coder-next:q4_K_M
    apiBase: http://aperture/v1

    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      temperature: 0.2
      maxTokens: 8192

  - name: GB10 Planning
    provider: openai
    model: qwen3.8:latest
    apiBase: http://aperture/v1

    roles:
      - chat
    defaultCompletionOptions:
      temperature: 0.2
      maxTokens: 12288

  # Blackwell models
  - name: Blackwell Coder
    provider: openai
    model: qwen2.5-coder:14b
    apiBase: http://aperture/v1

    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      temperature: 0.2
      maxTokens: 4096

  - name: Blackwell FIM Autocomplete
    provider: ollama
    model: qwen2.5-coder:1.5b-base
    apiBase: http://pro-max-plus:11435
    roles:
      - autocomplete
    autocompleteOptions:
      debounceDelay: 200
      maxPromptTokens: 1024
      onlyMyCode: true


