services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main-slim
    container_name: open-webui
    restart: always

    ports:
      - "3000:8080"

    environment:
      OLLAMA_BASE_URL: http://ollama:11435

    volumes:
      - "${CONTAINER_DATA_DIR:-/container_data}/open-webui/open-webui-data:/app/backend/data"

    depends_on:
      ollama:
        condition: service_healthy
      ollama-init:
        condition: service_completed_successfully